baseurl: "/"
url: ""
local_theme: safex

emptyArray: []

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename/
  - scope:
      path: "_categories"
    values:
      layout: page
      bottomInclude: services.liquid
  - scope:
      path: "_services"
    values:
      layout: page-post
  - scope:
      path: "_smoki"
    values:
      layout: page-collection
      useCustomSingleNodePage: true
      galleryOnlyInLeafNodes: false
      hideItselfInFileList: true
      removeIndexFromFilename: true
      displayLeafDirectoriesAsFiles: true
      subtitle: Dzień dobry

collections:
  services:
    output: true
    permalink: /oferta/:path/
  categories:
    output: true
    permalink: /oferta/:path/
  smoki:
    output: true

include:
  - _pages

plugins:
  - jekyll-local-theme

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - tailwind.config.js
  - package.json
  - package-lock.json
  - assets/css/
  - assets/images_source
  - image-converter.js
  - postinstall.js
