baseurl: "/"
url: ""

emptyArray: []

plugins:
  - jekyll-local-theme

local_theme: safex

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename/
      heroImage: assets/images/bg1
      layout: page
  - scope:
      path: "_oferta"
    values:
      layout: page-collection
  - scope:
      path: "_baza-wiedzy"
    values:
      layout: page-collection

collections:
  oferta:
    output: true
  baza-wiedzy:
    output: true

include:
  - _pages

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - tailwind.config.js
  - package.json
  - package-lock.json
  - assets/scss/
  - README.md
  - readme-img-1.png
  - readme-img-2.png
  - readme-img-3.png
  - readme-img-4.png
