on:
  push

name: Build and deploy website

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node deps
        #run: npm install
        run: echo "npm install"
      - name: Build images
        #run: node image-converter.mjs
        run: |
          mkdir assets/images
          touch assets/images/testfile.txt
          echo test > assets/images/testfile.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: assets/images

  build-website:
    name: Build website
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-images
          path: assets/images
      - name: List files
        run: |
          ls -la
          ls -la assets/images
      - name: Build website
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-website
          path: _site

  upload:
    name: Upload to FTP
    needs: build-website
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-website
      - name: List files
        run: ls -la _site

#      - name: upload files
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#        with:
#          server: ${{ secrets.FTP_SERVER }}
#          username: ${{ secrets.FTP_USER }}
#          password: ${{ secrets.FTP_PASS }}
#          server-dir: wp-content/themes/safex-twentytwentyfour/
#          local-dir: safex-twentytwentyfour/
