on:
  push

name: Build and deploy website

jobs:
  build:
    name: Build with Jekyll
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: some-output-file
          path: _config.yml

  upload:
    name: Upload to FTP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: some-output-file
      - name: display result
        run: | 
          cat _config.yml
          ls -la

#      - name: upload files
#        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#        with:
#          server: ${{ secrets.FTP_SERVER }}
#          username: ${{ secrets.FTP_USER }}
#          password: ${{ secrets.FTP_PASS }}
#          server-dir: wp-content/themes/safex-twentytwentyfour/
#          local-dir: safex-twentytwentyfour/
